### ISSUE TITLE
SSR : Window is not defined!

### ISSUE THREAD

**Issue by checkraiser** [netguru/react_webpack_rails#50]
I've tried the command: 
```
npm run rwr-node-dev-server
```

But got error:

```
window.RWR = _reactWebpackRails2.default;
^

ReferenceError: window is not defined
    at Object.<anonymous> (index.js:2:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/checkraiser/Code/testwp/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/checkraiser/Code/testwp/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/checkraiser/Code/testwp/app/react/node_server.js:4:1)
    at Module._compile (module.js:413:34)
error: Forever detected script exited with code: 1
```

Do you know how to resolve the error ?

**Comment by mxaly** [comment]
hey, it's not yet released and we will point this in generator and add migrations steps describing what is going on when the v0.2.0 will be ready. 
We recommend using v0.1.2 for now unless you are just testing new stuff. If so, replace `window.RWR = RWR` in index with `RWR.run()`

**Comment by mxaly** [comment]
see https://github.com/netguru/react_webpack_rails/tree/0.1-stable for last release and it's docs

**Comment by checkraiser** [comment]
I clone the current repo into local gem folder.
And i got the error:
```
error: Could not read .foreverignore file.
error: ENOENT: no such file or directory, open 'app/react/.foreverignore'
/Users/checkraiser/Code/testwp/app/react/index.js:13
_reactWebpackRails2.default.run();
                            ^

TypeError: _reactWebpackRails2.default.run is not a function
    at Object.<anonymous> (index.js:2:5)
    at Module._compile (module.js:413:34)
    at loader (/Users/checkraiser/Code/testwp/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/checkraiser/Code/testwp/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/checkraiser/Code/testwp/app/react/node_server.js:4:1)
    at Module._compile (module.js:413:34)
error: Forever detected script exited with code: 1
```

**Comment by mxaly** [comment]
Looks like it's using old version of react-webpack-rails package. As i said - master is a development branch, we use local build when developing. We will make sure that everything will work super fine before release. Stay tuned!

**Comment by checkraiser** [comment]
Thank you @mxaly !
