### ISSUE TITLE
rails generate react_webpack_rails:install:server_side error

### ISSUE THREAD

**Issue by wasabia** [netguru/react_webpack_rails#55]
when i upgrade  react_webpack_rails to 0.2.0, exec commend 
```
rails generate react_webpack_rails:install:server_side
```

i got a error.

it is 

```
    def load_json(file)
        JSON.load(Rails.root.join(file))
      end
```

maybe we need use read the file then load..

```

  ~/bnbtrip/bnbTrip-server   master ●  rails generate react_webpack_rails:install:server_side
   identical  tmp/packages/server-side.json
/Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/react_webpack_rails-0.2.0/lib/generators/react_webpack_rails/merge_helpers.rb:9:in `load': unexpected characters after the JSON document at line 12, column 2 [sparse.c:607] (Oj::ParseError)
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/react_webpack_rails-0.2.0/lib/generators/react_webpack_rails/merge_helpers.rb:9:in `load_json'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/react_webpack_rails-0.2.0/lib/generators/react_webpack_rails/merge_helpers.rb:16:in `merge_into_package'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/react_webpack_rails-0.2.0/lib/generators/react_webpack_rails/install/server_side_generator.rb:17:in `package'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/generators.rb:157:in `invoke'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/zhaolei/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by wasabia** [comment]
https://github.com/netguru/react_webpack_rails/pull/56

**Comment by mxaly** [comment]
@wasabia can you share you package.json?

**Comment by wasabia** [comment]
Maybe like this....
```
{
  "devDependencies": {
    "apidoc": "^0.14.0",
    "babel-eslint": "^4.1.3",
    "css-loader": "^0.23.0",
    "eslint": "^1.7.3",
    "eslint-plugin-react": "^3.6.3",
    "expect": "^1.13.2",
    "karma": "^0.13.13",
    "karma-chrome-launcher": "^0.2.1",
    "karma-mocha": "^0.2.0",
    "karma-sinon": "^1.0.4",
    "karma-sourcemap-loader": "^0.3.6",
    "karma-webpack": "^1.7.0",
    "react-hot-loader": "^1.3.0",
    "webpack-dev-server": "^1.12.1",
    "webpack-notifier": "^1.2.1"
  },
  "dependencies": {
    "alt": "^0.17.9",
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "classnames": "^2.2.1",
    "extract-text-webpack-plugin": "^0.9.1",
    "google-map-react": "^0.9.3",
    "history": "^2.0.0-rc2",
    "moment": "^2.10.6",
    "node-sass": "^3.3.3",
    "photoswipe": "^4.1.0",
    "rc-calendar": "^5.1.0",
    "rc-slider": "^3.1.4",
    "react": "^0.14.5",
    "react-autosuggest": "^2.2.3",
    "react-day-picker": "^1.2.0",
    "react-dom": "^0.14.5",
    "react-ga": "^1.2.0",
    "react-paginate": "^0.4.3",
    "react-router": "^2.0.0-rc5",
    "react-tap-event-plugin": "^0.2.1",
    "react-tools": "*",
    "react-webpack-rails": "^0.2.0",
    "sass-loader": "^3.0.0",
    "underscore": "^1.8.3",
    "webpack": "^1.12.1"
  },
  "scripts": {
    "test": "karma start",
    "start": "webpack -w --config webpack/dev.config.js",
    "start-hot-dev": "webpack-dev-server --hot --inline --config webpack/hot-dev.config.js",
    "build": "webpack -p --config webpack/production.config.js",
    "apidoc": "apidoc -i app/controllers/partner/ -o apidoc/"
  }
}

```

**Comment by mxaly** [comment]
#56 merged. Thanks  @wasabia!
