### ISSUE TITLE
Rails throwing a connection error 

### ISSUE THREAD

**Issue by bechirsegni** [netguru/react_webpack_rails#59]
Errno::ECONNREFUSED in ReactExamples#component

Failed to open TCP connection to localhost:8081 (Connection refused - connect(2) for "localhost" port 8081)

I followed the steps as the documentation but that's what i get each time i start rails server and npm start

**Comment by mxaly** [comment]
By default, generator will setup server side render and add it to generated example.  This require node server to be up and running. 
To fix your issue remove `server_side: true` from `app/views/react_examples/component.html.erb` or run node server: `$ npm run rwr-node-dev-server` 
Check [here for more about server-side render](https://github.com/netguru/react_webpack_rails/blob/master/docs/server_side_rendering.md)

Anyway, thanks for pointing this out. We will update readme.

**Comment by bechirsegni** [comment]
Yes i Already Tried this even with that on fresh install i receive the same error , plus when i run 
`$ npm run rwr-node-dev-server`

```
`error: Could not read .foreverignore file.
error: ENOENT: no such file or directory, open 'app/react/.foreverignore'
/home/bechir/Sites/ReactNetguru/app/react/index.js:13
_reactWebpackRails2.default.run();
                            ^

TypeError: _reactWebpackRails2.default.run is not a function
    at Object.<anonymous> (index.js:2:5)
    at Module._compile (module.js:413:34)
    at loader (/home/bechir/Sites/ReactNetguru/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/bechir/Sites/ReactNetguru/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bechir/Sites/ReactNetguru/app/react/node_server.js:4:1)
    at Module._compile (module.js:413:34)
error: Forever detected script exited with code: 1
`
```

**Comment by mxaly** [comment]
there is wrong react-webpack-rails package version in generator. It's already fixed but not released yet. 
replace`"react-webpack-rails": "0.1.0",` with "react-webpack-rails": "^0.2.0",` or wait for fix - we are currently preparing it.

**Comment by bechirsegni** [comment]
Great  Thank you
