### ISSUE TITLE
undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by kalashnikovisme** [netguru/react_webpack_rails#93]
After install gem and `rails g react_webpack_rails:install` I have this error:

```ruby
undefined method `keys' for nil:NilClass
```

on this line

```ruby
= javascript_include_tag 'application'
```

**Comment by mxaly** [comment]
Hi @kalashnikovisme 
which  version of Rails? 4,5?

**Comment by kalashnikovisme** [comment]
@mxaly Rails 4.2.3

**Comment by mxaly** [comment]
Checking this with fresh app. Can you also share your `application.js` content?
Is it failing when you will remove 
```js 
//= require react_integration
//= require react_bundle
``` 
from it?

**Comment by mxaly** [comment]
It works fine @kalashnikovisme  for new rails 4 app. 
Please make sure that this error wasn't there before generating. If it wasn't and you sure that it's related with our gem, let me know pls.

**Comment by kalashnikovisme** [comment]
@mxaly 

* I haven't this error before.
* It's failing after remove

```javascript
//= require react_integration
//= require react_bundle
```

* Stack trace

```
NoMethodError - undefined method `keys' for nil:NilClass:
  react-rails (1.3.1) lib/react/jsx/babel_transformer.rb:8:in `initialize'
  react-rails (1.3.1) lib/react/jsx.rb:19:in `transform'
  react-rails (1.3.1) lib/react/jsx/template.rb:13:in `evaluate'
  tilt (2.0.1) lib/tilt/template.rb:96:in `render'
  sprockets (3.4.0) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.4.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.4.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.4.0) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.4.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.4.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.4.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.4.0) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.4.0) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.4.0) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.4.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.4.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.4.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.4.0) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.4.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.4.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.4.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.4.0) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.4.0) lib/sprockets/environment.rb:30:in `find_asset'
  sprockets (3.4.0) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:137:in `block in javascript_include_tag'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:136:in `javascript_include_tag'
  app/views/layouts/application.html.slim:7:in `_app_views_layouts_application_html_slim__2375968872894422707_52819900'
```

* react-rails gem working fine in app. Version 1.3.1. May be I should update it?

**Comment by mxaly** [comment]
@kalashnikovisme react_webpack_rails is a alternative for react-rails. It's not made to work together with it. 

If you want, please describe what is your goal here. Maybe i can help solving it.

**Comment by mxaly** [comment]
Or we can try some sort of screen-share (skype/hangouts) - i'm happy to help:)

**Comment by kalashnikovisme** [comment]
@mxaly after remove `react-rails` from Gemfile this error has disappear.
Please, add note to Readme or docs about incompatibility with react-rails gem.

If any other issue will appear, I'll create new issue for this. Thank you!
