### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by kalashnikovisme** [netguru/react_webpack_rails#97]
I've runned `npm run rwr-node-dev-server` and have error

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
error: Could not read .foreverignore file.
error: ENOENT, open 'app/react/.foreverignore'

/home/pavel/projects/happy-crm/app/react/node_server.js:12
    console.log(`started: ${request.method} "${request.url}" at ${new Date().t
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
error: Forever detected script exited with code: 8
```

```
react_webpack_rails (0.4.1)
```

**Comment by kalashnikovisme** [comment]
After adding empty `.foreverignore` error looks like this:

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms

/home/pavel/projects/happy-crm/app/react/node_server.js:12
    console.log(`started: ${request.method} "${request.url}" at ${new Date().t
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
error: Forever detected script exited with code: 8
```

**Comment by mxaly** [comment]
Looks like you are using old node. You can check compatibility at http://node.green/.
Update you node version or if it's not possible, replace template literals with standard string:
```js
console.log(`started: ${request.method} "${request.url}" at ${new Date().toLocaleTimeString()}`);
``` with:
```js
console.log('started: ' + request.method + ' "${request.url}" at ' + new Date().toLocaleTimeString());
```

**Comment by kalashnikovisme** [comment]
@mxaly after updating nodejs to version 4.4.3 everything is ok. Thanks!
